<?php

/* Stack Mobile - Bringing Stack Exchange Sites to Mobile Devices
   Copyright (C) 2012  Nathan Osman

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>. */

?>
<h3>About <?php echo $config['site_name']; ?></h3>
<p>
  <?php echo $config['site_name']; ?> is a mobile-friendly front-end to the <a href='http://stackexchange.com'>
  Stack Exchange</a> network of sites.
</p>
<p>
  <?php echo $config['site_name']; ?> uses the <a href="http://stackapps.com">public API</a> provided
  by Stack Exchange to retrieve its content.
</p>
<h3>About the Content</h3>
<p>
  All user content on <?php echo $config['site_name']; ?> is licensed under a
  <a href="http://creativecommons.org/licenses/by-sa/3.0/">cc-wiki with attribution</a>
  license. <?php echo $config['site_name']; ?> is not responsible for third party content
  retrieved from Stack Exchange and makes no claims as to its accuracy.
</p>
<h3>About the Author</h3>
<p>
  <?php echo $config['site_name']; ?> is powered by <a href='https://github.com/nathan-osman/Stack-Mobile'>
  Stack Mobile</a>, though it is not affiliated with Stack Mobile or <a href='http://stackmobile.com'>
  stackmobile.com</a> in any way. The Stack Mobile software uses <a href="http://php.net">PHP</a>
  and <a href="http://jquerymobile.com">jQuery Mobile</a>. You can find other
  projects from the same author <a href="http://quickmediasolutions.com">here</a>.
</p>
