<?php

/* Stack Mobile - Bringing Stack Exchange Sites to Mobile Devices
   Copyright (C) 2012  Nathan Osman

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>. */

// Represents a form field
class Field
{
   public $name;          // the name of the field
   public $friendly_name; // the human-readable name
   public $description;   // a description of the field
   
   // Handy constructor
   function __construct($name, $friendly_name, $description)
   {
       $this->name          = $name;
       $this->friendly_name = $friendly_name;
       $this->description   = $description;
   }
}

// These are the fields that need to be filled in
$fields = array(new Field('site_name', 'Site name', 'The name of the site as it will appear in page titles and search results. Note: you may <b>not</b> use the name "Stack Mobile" or "stackmobile.com".</b>'),
                new Field('admin_email', 'Administrator email', 'The email address of the site administrator or webmaster. This address will be shown on error pages and in the about page.'),
                new Field('api_key', 'API key', 'The API key that Stack Mobile uses to retrieve data from the Stack Exchange API.'),
                new Field('db_host', 'PDO host string', 'The PDO string that contains the connection information for the database that Stack Mobile requires.'),
                new Field('db_username', 'Database username', 'The username for connecting to the database.'),
                new Field('db_password', 'Database password', 'The password for connecting to the database.'));

// Determine whether we are generating the form or processing it
$postback = ($_SERVER['REQUEST_METHOD'] == 'POST');

// Ensure the requirements are met
$general_errors = array();

$version = explode('.', phpversion());
if($version[0] < '5' ||
   $version[1] < '2')
    $general_errors[] = 'Error: Stack Mobile requires PHP 5.2+ but the installer detected ' . phpversion() . '.';

if(!extension_loaded('pdo'))
    $general_errors[] = 'Error: the PDO extension is not loaded.';

// Generate the HTML for the fields
$all_fields_provided = TRUE;
$fields_html = array();

foreach($fields as $field)
{
    // Display any errors for that field and display the current value for the field if provided
    $error_details = '';
    $current_value = '';
    
    if($postback)
    {
        if(!isset($_POST[$field->name]) || $_POST[$field->name] == '')
        {
            $error_details = '<span class="error"> this field is required</span>';
            $all_fields_provided = FALSE;
        }
        else
            $current_value = htmlentities($_POST[$field->name]);
    }
    
    $fields_html[] = "<tr><td>{$field->friendly_name}</td><td><input type='text' id='{$field->name}' name='{$field->name}' data-description='{$field->description}' value='$current_value' onfocus='ShowPopup(event);' onblur='HidePopup();' /></td><td>$error_details</td></tr>";
}

// If this is a postback, and each field was provided, then we can write the config file
if($postback && $all_fields_provided && !count($general_errors))
{
    // Make an attempt to connect to the specified database to ensure the string is valid
    try
    {
        $pdo = new PDO($_POST['db_host'], $_POST['db_username'], $_POST['db_password']);
        
        // Now attempt to open the configuration file.
        $file = @fopen('../config.php', 'w');
        
        if($file)
        {
            // Write the file header
            fwrite($file, "<?php\n\n// Configuration file generated by installer " . date(DATE_RFC1123) . "\n\n");
            
            // Write each configuration value to the config.php file
            foreach($fields as $field)
                fwrite($file, '$config[\'' . $field->name . '\'] = "' . str_replace('"', '\"', $_POST[$field->name]) . '";' . "\n");
            
            fwrite($file, "\n?>");
            fclose($file);
            
            // Display the message
            echo "<p>Configuration file written successfully!</p><p>Please rename or remove the 'install/' directory to continue.</p>";
            exit;
        }
        else
            $general_errors[] = 'Error: cannot open "config.php" for writing.';
    }
    catch(PDOException $e)
    {
        $general_errors[] = 'Error: PDO constructor returned "' . $e->getMessage() . '".';
    }
}

?>
<!DOCTYPE html>
<html>
<head>
  <title>Stack Mobile Installation</title>
  <style>
  
  body {
      font-family: arial, helvetica, sans;
  }
  
  h2 {
      color: #777;
      border-bottom: 1px solid #777;
  }
  
  tr td:first-child {
      color: #777;
      text-align: right;
  }
  
  input[type=submit] {
      padding: 4px 12px;
  }
  
  .error {
      color: red;
  }
  
  #popup {
      display: none;
      position: absolute;
      width: 180px;
      background-color: #fff;
      border: 1px solid #555;
      border-radius: 0px 16px 16px;
      box-shadow: 3px 3px 8px #aaa;
      padding: 6px;
      font-size: 10pt;
      z-index: 1;
  }
  
  </style>
  <script>
  
  function ShowPopup(event) {
      
      var popup = document.getElementById('popup');
      var rect = event.srcElement.getBoundingClientRect();
      var description = event.srcElement.getAttribute('data-description');
      
      // Position the popup
      var x = rect.left + rect.width + 5;
      var y = rect.top;
      
      popup.style['left'] = x + 'px';
      popup.style['top'] = y + 'px';
      
      // Set the content of the popup and display it
      popup.innerHTML = description;
      popup.style['display'] = 'block';
      
  }
  
  function HidePopup() {
      
      document.getElementById('popup').style['display'] = 'none';
      
  }
  
  </script>
</head>
<body>
  <h2>Stack Mobile Installation</h2>
  <p>Please fill in the form below to complete the installation of Stack.PHP.</p>
  <?php
  
  // Display a general error if one was set
  if(count($general_errors))
      echo '<p class="error">' . implode('<br />', $general_errors) . '</p>';
  
  ?>
  <form method='post'>
    <table>
      <?php echo implode('', $fields_html); ?>
    </table>
    <p>Once you are sure that these settings are correct, click below to begin the installation.</p>
    <input type='submit' value='Install' />
  </form>
  <div id='popup'></div>
</body>
</html>